function [ELFORCE]= elforcecalc(COORDS,PVEC,GWEI,PHIMAT,PHICMAT,PHIEMAT)
DXDC=PHICMAT*COORDS(:,1);
DXDE=PHIEMAT*COORDS(:,1);
DYDC=PHICMAT*COORDS(:,2);
DYDE=PHIEMAT*COORDS(:,2);
AJACOB=(DXDC.*DYDE-DXDE.*DYDC);
WTVEC=GWEI.*AJACOB;
ELFORCE=(WTVEC')*PHIMAT*PVEC;
end